name: Lint

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  run-linters:
    runs-on: ubuntu-latest, windows-latest, macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true